#ifndef LQAUXILIARYTOOLS_GLOBAL_H
#define LQAUXILIARYTOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LQTOOLS_LIBRARY)
#  define LQTOOLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LQTOOLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LQAUXILIARYTOOLS_GLOBAL_H
