#ifndef LQFORMWIDGET_GLOBAL_H
#define LQFORMWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LQFORMWIDGET_LIBRARY)
#  define LQFORMWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LQFORMWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LQFORMWIDGET_GLOBAL_H
