#ifndef LQLEDINDICATOR_GLOBAL_H
#define LQLEDINDICATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LQLEDINDICATOR_LIBRARY)
#  define LQLEDINDICATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LQLEDINDICATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LQLEDINDICATOR_GLOBAL_H
